services:
  - type: web
    name: users-management-api
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /swagger-ui/index.html
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_ENGINE
        value: "mysql"
      - key: DB_HOST
        value: "proyecto-spring-proyecto-spring.i.aivencloud.com"
      - key: DB_PORT
        value: "18105"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USERNAME
        value: "avnadmin"
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: REQUIRED
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: "gomezeliecer83@gmail.com"
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_ADDRESS
        value: "gomezeliecer83@gmail.com"
      - key: SMTP_FROM_NAME
        value: Gestion de Usuarios
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_SECONDS
        value: "900"
